server:
  port: 8088



spring:
  elasticsearch:
    uris: http://localhost:9200




  main:
    allow-circular-references: true
#elasticsearch
#elasticsearch:
#  schema: http
#  address: 127.0.0.1:9200
#  connectTimeout: 5000
#  socketTimeout: 5000
#  connectionRequestTimeout: 5000
#  maxConnectNum: 100
#  maxConnectPerRoute: 100